<a href="https://www.kaggle.com/code/alaaazazi/wine-dataset-for-clustering?scriptVersionId=258688538" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/kaggle/input/wine-dataset-for-clustering/wine-clustering.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
dtypes: float64(11), int64(2)
memory usage: 18.2 KB


In [3]:
data.dropna(axis=0, inplace=True)
print(data.isna().count)


<bound method DataFrame.count of      Alcohol  Malic_Acid    Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      False       False  False         False      False          False   
1      False       False  False         False      False          False   
2      False       False  False         False      False          False   
3      False       False  False         False      False          False   
4      False       False  False         False      False          False   
..       ...         ...    ...           ...        ...            ...   
173    False       False  False         False      False          False   
174    False       False  False         False      False          False   
175    False       False  False         False      False          False   
176    False       False  False         False      False          False   
177    False       False  False         False      False          False   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Inte

In [4]:
data

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

In [5]:
def calc_mean(data):
    mean = np.mean(data, axis=0)  
    return mean
Mean = calc_mean(data)
Mean 

Alcohol                  13.000618
Malic_Acid                2.336348
Ash                       2.366517
Ash_Alcanity             19.494944
Magnesium                99.741573
Total_Phenols             2.295112
Flavanoids                2.029270
Nonflavanoid_Phenols      0.361854
Proanthocyanins           1.590899
Color_Intensity           5.058090
Hue                       0.957449
OD280                     2.611685
Proline                 746.893258
dtype: float64

In [6]:
def calc_covariance_matrix(data, mean):
   
    shifted_data = data - mean  
    print("Shifted Feature Vectors (F - m):\n", shifted_data)
    
    covariance_matrix = np.cov(shifted_data.T)  
    return covariance_matrix, shifted_data
cov_matrix, shifted_data = calc_covariance_matrix(data, Mean)


Shifted Feature Vectors (F - m):
       Alcohol  Malic_Acid       Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    1.229382   -0.626348  0.063483     -3.894944  27.258427       0.504888   
1    0.199382   -0.556348 -0.226517     -8.294944   0.258427       0.354888   
2    0.159382    0.023652  0.303483     -0.894944   1.258427       0.504888   
3    1.369382   -0.386348  0.133483     -2.694944  13.258427       1.554888   
4    0.239382    0.253652  0.503483      1.505056  18.258427       0.504888   
..        ...         ...       ...           ...        ...            ...   
173  0.709382    3.313652  0.083483      1.005056  -4.741573      -0.615112   
174  0.399382    1.573652  0.113483      3.505056   2.258427      -0.495112   
175  0.269382    1.943652 -0.106517      0.505056  20.258427      -0.705112   
176  0.169382    0.253652  0.003483      0.505056  20.258427      -0.645112   
177  1.129382    1.763652  0.373483      5.005056  -3.741573      -0.245112   

     Flavanoids  

In [7]:
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
 [[ 6.59062328e-01  8.56113090e-02  4.71151590e-02 -8.41092903e-01
   3.13987812e+00  1.46887218e-01  1.92033222e-01 -1.57542595e-02
   6.35175205e-02  1.02828254e+00 -1.33134432e-02  4.16978226e-02
   1.64567185e+02]
 [ 8.56113090e-02  1.24801540e+00  5.02770393e-02  1.07633171e+00
  -8.70779534e-01 -2.34337723e-01 -4.58630366e-01  4.07333619e-02
  -1.41146982e-01  6.44838183e-01 -1.43325638e-01 -2.92447483e-01
  -6.75488666e+01]
 [ 4.71151590e-02  5.02770393e-02  7.52646353e-02  4.06208278e-01
   1.12293658e+00  2.21455913e-02  3.15347299e-02  6.35847140e-03
   1.51557799e-03  1.64654327e-01 -4.68215451e-03  7.61835841e-04
   1.93197391e+01]
 [-8.41092903e-01  1.07633171e+00  4.06208278e-01  1.11526862e+01
  -3.97476036e+00 -6.71149146e-01 -1.17208281e+00  1.50421856e-01
  -3.77176220e-01  1.45024186e-01 -2.09118054e-01 -6.56234368e-01
  -4.63355345e+02]
 [ 3.13987812e+00 -8.70779534e-01  1.12293658e+00 -3.97476036e+00
   2.03989335e+02  1.91646988e+00  2.79308703e

In [8]:
def calculate_eign_value(cov_matrix):
    
    coeffs = np.poly(cov_matrix)
    
    eign_values = np.roots(coeffs)
    return eign_values

eign_values = calculate_eign_value(cov_matrix)
print(eign_values.shape)
print(eign_values)

(13,)
[9.92017895e+04 1.72535266e+02 9.43811370e+00 4.99117861e+00
 1.22884523e+00 8.41063869e-01 2.78973523e-01 1.51381266e-01
 1.12096765e-01 7.17026032e-02 3.75759789e-02 2.10723661e-02
 8.20370314e-03]


In [9]:
def calculate_eign_vectors(cov_matrix, eign_values):
    n = cov_matrix.shape[0]
    eig_vectors = []
    for eig_val in eign_values:
        eig_vec_matrix = eig_val * np.eye(n) - cov_matrix
        # use SVD (singular value decomposition) to solve the equation of eig_vec_matrix to get eign vector
        _, _, vh = np.linalg.svd(eig_vec_matrix)
        eig_vector = vh[-1] # last row in vh is the eign vector we seek
        eig_vector = eig_vector / np.linalg.norm(eig_vector)
        eig_vectors.append(eig_vector)
    eign_vectors = np.array(eig_vectors).T
    return eign_vectors
eign_vectors = calculate_eign_vectors(cov_matrix, eign_values)

eign_vectors

array([[-1.65926472e-03,  1.20340617e-03,  1.68738094e-02,
         1.41446778e-01, -2.03369773e-02, -1.94120104e-01,
        -9.23280337e-01,  2.84820658e-01, -8.66006124e-02,
        -2.24499994e-03,  1.49715080e-02, -1.56514071e-02,
        -8.02924535e-03],
       [ 6.81015556e-04,  2.15498184e-03,  1.22003373e-01,
         1.60389543e-01,  6.12883454e-01, -7.42472963e-01,
         1.50109941e-01, -6.46744678e-02, -1.56621385e-02,
        -1.85093501e-02,  2.31876506e-02,  6.72955455e-02,
         1.10903923e-02],
       [-1.94905742e-04,  4.59369254e-03,  5.19874304e-02,
        -9.77280992e-03, -2.01755752e-02, -4.17529118e-02,
        -4.50095493e-02, -1.49339532e-01, -7.36498524e-02,
        -8.67996529e-02, -9.54010643e-01, -1.32063034e-01,
         1.73685673e-01],
       [ 4.67130058e-03,  2.64503930e-02,  9.38593003e-01,
        -3.30965260e-01, -6.43523403e-02,  2.40653026e-02,
        -3.15265835e-02,  1.51539118e-02, -2.04457785e-03,
         3.55402799e-03,  5.28216953e

In [10]:
def calculate_explained_variance(eigenvalues):
    total_variance = np.sum(eigenvalues)
    explained_variance = eigenvalues / total_variance
    return explained_variance

explained_variance = calculate_explained_variance(eign_values)
print("Explained Variance:", explained_variance)

Explained Variance: [9.98091230e-01 1.73591562e-03 9.49589576e-05 5.02173562e-05
 1.23636847e-05 8.46213034e-06 2.80681456e-06 1.52308053e-06
 1.12783044e-06 7.21415811e-07 3.78060267e-07 2.12013755e-07
 8.25392788e-08]


In [11]:
def construct_q_matrix(eigenvalues, eigenvectors, n_components):
    
    idx = np.argsort(eigenvalues)[::-1]
    
 
    eigenvectors_sorted = eigenvectors[:, idx]
    
  
    eigenvectors_normalized = eigenvectors_sorted / np.linalg.norm(eigenvectors_sorted, axis=0)
    
    
    q_matrix = eigenvectors_normalized[:, :n_components]
    return q_matrix

n_components = 5# Example: reduce to 2 components
q_matrix = construct_q_matrix(eign_values, eign_vectors, n_components)
print("Q Matrix:\n", q_matrix)

Q Matrix:
 [[-1.65926472e-03  1.20340617e-03  1.68738094e-02  1.41446778e-01
  -2.03369773e-02]
 [ 6.81015556e-04  2.15498184e-03  1.22003373e-01  1.60389543e-01
   6.12883454e-01]
 [-1.94905742e-04  4.59369254e-03  5.19874304e-02 -9.77280992e-03
  -2.01755752e-02]
 [ 4.67130058e-03  2.64503930e-02  9.38593003e-01 -3.30965260e-01
  -6.43523403e-02]
 [-1.78680075e-02  9.99344186e-01 -2.97802484e-02 -5.39375605e-03
   6.14934472e-03]
 [-9.89829680e-04  8.77962152e-04 -4.04846439e-02 -7.45846556e-02
  -3.15245063e-01]
 [-1.56728830e-03 -5.18507284e-05 -8.54433387e-02 -1.69086724e-01
  -5.24761088e-01]
 [ 1.23086662e-04 -1.35447892e-03  1.35107797e-02  1.08055610e-02
   2.96475124e-02]
 [-6.00607792e-04  5.00440040e-03 -2.46593824e-02 -5.01209524e-02
  -2.51182529e-01]
 [-2.32714319e-03  1.51003530e-02  2.91398464e-01  8.78893693e-01
  -3.31747051e-01]
 [-1.71380037e-04 -7.62673115e-04 -2.59776624e-02 -6.00349446e-02
  -5.15240771e-02]
 [-7.04931645e-04 -3.49536431e-03 -7.03239693e-02 -1.7

In [12]:
def transform(q, shifted_data):
    transformed_data = np.dot(shifted_data, q)
    return transformed_data

transformed_data = transform(q_matrix, shifted_data)
print("Transformed Data :\n", transformed_data)

Transformed Data :
 [[-3.18562979e+02  2.14921307e+01 -3.13073470e+00  2.50113758e-01
  -6.77078222e-01]
 [-3.03097420e+02 -5.36471768e+00 -6.82283550e+00  8.64034749e-01
   4.86095978e-01]
 [-4.38061133e+02 -6.53730945e+00  1.11322298e+00 -9.12410681e-01
  -3.80651426e-01]
 [-7.33240139e+02  1.92729032e-01  9.17257016e-01  5.41250645e-01
  -8.58662289e-01]
 [ 1.15714285e+01  1.84899946e+01  5.54422076e-01 -1.36089609e+00
  -2.76441556e-01]
 [-7.03231192e+02 -3.32158674e-01 -9.49375334e-01  3.59993827e-01
  -1.56827100e-01]
 [-5.42971581e+02 -1.35189666e+01 -2.12694283e+00 -5.55661430e-02
   4.83659661e-01]
 [-5.48401860e+02  1.14494324e+01 -4.04924202e-02 -1.34945380e+00
   8.52590856e-01]
 [-2.98036863e+02 -8.18015784e+00 -3.88097517e+00  9.10643037e-01
  -3.11488981e-01]
 [-2.98049553e+02 -7.10154294e+00 -1.55845533e+00  1.67704202e+00
  -1.55841608e+00]
 [-7.63079712e+02 -8.33431723e+00  1.88629037e+00 -1.59831835e+00
   2.77175370e-01]
 [-5.32943228e+02 -1.42876338e+01 -1.30335240

In [13]:
transformed_data.shape

(178, 5)

In [14]:
def inverse_transform(q, transformed_data, mean):
    mean_reshaped = np.tile(mean, (transformed_data.shape[0], 1))  
    original_data = np.dot( transformed_data ,q.T) + mean_reshaped
    return original_data

inverse_transformed_data = inverse_transform(q_matrix, transformed_data, Mean)
print("Inverse Transformed Data :\n", inverse_transformed_data)

Inverse Transformed Data :
 [[1.35513821e+01 1.40890252e+00 2.37579212e+00 ... 1.09685274e+00
  3.11319616e+00 1.06500132e+03]
 [1.34942829e+01 1.72246677e+00 2.02799542e+00 ... 1.11380920e+00
  3.04324201e+00 1.04999989e+03]
 [1.36170784e+01 1.78011495e+00 2.49633737e+00 ... 1.08298051e+00
  3.12685706e+00 1.18500003e+03]
 ...
 [1.38681159e+01 4.01077615e+00 2.51789195e+00 ... 5.56273019e-01
  1.31642255e+00 8.34999500e+02]
 [1.37273756e+01 3.29581137e+00 2.52163535e+00 ... 6.75807359e-01
  1.75334446e+00 8.39998290e+02]
 [1.32765670e+01 3.70286038e+00 2.58801740e+00 ... 5.71168200e-01
  1.46763544e+00 5.60001632e+02]]


In [15]:
inverse_transformed_data.shape

(178, 13)

In [16]:
def reconstruction_error(original_data, reconstructed_data):
    error = np.linalg.norm(original_data - reconstructed_data) / np.linalg.norm(original_data)
    return error

# Calculate reconstruction error for the current transformation
error = reconstruction_error(data, inverse_transformed_data)
print("reconstruction Error:", error)

reconstruction Error: 0.001506100815740048


In [17]:
for n_components in range(1, 13):  
    q_matrix = construct_q_matrix(eign_values, eign_vectors, n_components)
    transformed_data = transform(q_matrix, shifted_data)
    inverse_transformed_data = inverse_transform(q_matrix, transformed_data, Mean)
    error = reconstruction_error(data, inverse_transformed_data)
    print(f"N = {n_components}, Reconstruction Error: {error:.4f}")


N = 1, Reconstruction Error: 0.0168
N = 2, Reconstruction Error: 0.0051
N = 3, Reconstruction Error: 0.0034
N = 4, Reconstruction Error: 0.0020
N = 5, Reconstruction Error: 0.0015
N = 6, Reconstruction Error: 0.0010
N = 7, Reconstruction Error: 0.0008
N = 8, Reconstruction Error: 0.0006
N = 9, Reconstruction Error: 0.0005
N = 10, Reconstruction Error: 0.0003
N = 11, Reconstruction Error: 0.0002
N = 12, Reconstruction Error: 0.0001


In [18]:
def euclidean_distance(p, q):
    return np.sqrt(np.sum((p - q) ** 2))

In [19]:
def clustering(core_points, epsilon, min_points):
    clusters = []
    while core_points:
        cluster = [core_points.pop()]
        for p in cluster:
            for q in list(core_points):
                if close_neighbourhood(p, q, epsilon):
                    cluster.append(q)
                    # Remove q from core_points
                    core_points = [pt for pt in core_points if not np.array_equal(pt, q)]
        clusters.append(cluster)
    return clusters

In [20]:
def dbscan(points, epsilon, min_points):
    core_points, noise_points = find_core_points(points, epsilon, min_points)
    clusters = clustering(core_points, epsilon, min_points)
    return clusters, noise_points

In [21]:
def euclidean_distance_matrix(data):
    n = data.shape[0]
    distance_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            distance_matrix[i, j] = np.linalg.norm(data[i] - data[j])
    return distance_matrix

In [22]:
from sklearn.preprocessing import StandardScaler
data_scaled = StandardScaler().fit_transform(data)
distance_matrix = euclidean_distance_matrix(data_scaled)
print("Euclidean Distance Matrix:\n", distance_matrix)

Euclidean Distance Matrix:
 [[0.         3.49753522 3.02660794 ... 6.4909413  6.07878091 7.18442107]
 [3.49753522 0.         4.1429119  ... 6.39689969 6.09492714 7.36771922]
 [3.02660794 4.1429119  0.         ... 6.25367723 5.85179331 6.35388503]
 ...
 [6.4909413  6.39689969 6.25367723 ... 0.         1.82621785 3.39251526]
 [6.07878091 6.09492714 5.85179331 ... 1.82621785 0.         3.32427633]
 [7.18442107 7.36771922 6.35388503 ... 3.39251526 3.32427633 0.        ]]


In [23]:
distance_matrix.shape[0]

178

In [24]:
def eps_neighborhood_all(data, epsilon):
    distance_matrix = euclidean_distance_matrix(data)
    print(distance_matrix)
    neighborhoods = []
    
    for i in range(distance_matrix.shape[0]):
        neighborhood_indices = np.where(distance_matrix[i] <= epsilon)[0]
        neighborhoods.append(neighborhood_indices)
    
    return neighborhoods

epsilon = 2  

neighborhoods = eps_neighborhood_all(data_scaled, epsilon)
print(len(neighborhoods))
for i, neighborhood in enumerate(neighborhoods):
    print(f"Eps-neighborhood of point {i}:", neighborhood)

[[0.         3.49753522 3.02660794 ... 6.4909413  6.07878091 7.18442107]
 [3.49753522 0.         4.1429119  ... 6.39689969 6.09492714 7.36771922]
 [3.02660794 4.1429119  0.         ... 6.25367723 5.85179331 6.35388503]
 ...
 [6.4909413  6.39689969 6.25367723 ... 0.         1.82621785 3.39251526]
 [6.07878091 6.09492714 5.85179331 ... 1.82621785 0.         3.32427633]
 [7.18442107 7.36771922 6.35388503 ... 3.39251526 3.32427633 0.        ]]
178
Eps-neighborhood of point 0: [ 0 20 40 56]
Eps-neighborhood of point 1: [ 1 38]
Eps-neighborhood of point 2: [ 2 48]
Eps-neighborhood of point 3: [ 3  5 52 58]
Eps-neighborhood of point 4: [ 4 28]
Eps-neighborhood of point 5: [ 3  5 18 31 49 52 53 57 58]
Eps-neighborhood of point 6: [ 6  8 11 12 22 29 51]
Eps-neighborhood of point 7: [ 7 34 53]
Eps-neighborhood of point 8: [ 6  8 29 47]
Eps-neighborhood of point 9: [ 9 22 29 35 42 44 47 49 54 56 58]
Eps-neighborhood of point 10: [10 31 51]
Eps-neighborhood of point 11: [ 6 11 12 27 29 37 38]
Eps-

In [25]:
def classify_points(neighborhoods, min_pts):
    n = len(neighborhoods)
    core_points = []
    border_points = []
    noise_points = []
    
    # Determine core points
    for i in range(n):
        if len(neighborhoods[i]) >= min_pts:
            core_points.append(i)
    
    # Determine border and noise points
    for i in range(n):
        if i not in core_points:
            # Check if the neighborhood contains at least one core point
            if any(point in core_points for point in neighborhoods[i]):
                border_points.append(i)
            else:
                noise_points.append(i)
    
    return core_points, border_points, noise_points

min_pts = 5  
core_points, border_points, noise_points = classify_points(neighborhoods, min_pts)

# Output results
print("\nCore Points:", core_points)
print("Border Points:", border_points)
print("Noise Points:", noise_points)


Core Points: [5, 6, 9, 11, 12, 15, 17, 20, 22, 23, 24, 26, 27, 29, 31, 34, 35, 37, 38, 40, 44, 47, 48, 49, 52, 53, 54, 56, 57, 58, 81, 85, 88, 90, 91, 102, 104, 106, 116, 125, 131, 140, 142, 148, 162, 164]
Border Points: [0, 1, 2, 3, 7, 8, 10, 16, 18, 19, 28, 32, 33, 36, 42, 51, 55, 67, 80, 86, 89, 92, 97, 101, 103, 107, 108, 111, 113, 114, 117, 120, 126, 128, 132, 133, 139, 147, 156, 160, 161, 163, 167, 170, 171, 172, 174]
Noise Points: [4, 13, 14, 21, 25, 30, 39, 41, 43, 45, 46, 50, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 82, 83, 84, 87, 93, 94, 95, 96, 98, 99, 100, 105, 109, 110, 112, 115, 118, 119, 121, 122, 123, 124, 127, 129, 130, 134, 135, 136, 137, 138, 141, 143, 144, 145, 146, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 165, 166, 168, 169, 173, 175, 176, 177]


In [26]:
def dbscan_clustering(data, epsilon, min_pts):
    
    visited = set()  # Tracks visited points
    clusters = {}  # Dictionary to store clusters
    cluster_id = 0
    
    for point_idx in range(len(data)):
        if point_idx in visited or point_idx in noise_points:
            continue  # Skip already visited or noise points
        
        if point_idx in core_points:
            # Start a new cluster
            cluster_id += 1
            clusters[cluster_id] = []
            queue = [point_idx]  # Initialize a queue with the core point
            
            while queue:
                current_point = queue.pop(0)
                
                if current_point not in visited:
                    visited.add(current_point)
                    clusters[cluster_id].append(current_point)
                    
                    # Add neighbors to the cluster if they are core or border points
                    for neighbor in neighborhoods[current_point]:
                        if neighbor not in visited and neighbor not in queue:
                            if neighbor in core_points or neighbor in border_points:
                                queue.append(neighbor)
    
    return clusters, noise_points
clusters, noise_points = dbscan_clustering(data_scaled, epsilon, min_pts)

# Output results
print("\nClusters:")
for cluster_id, points in clusters.items():
    print(f"Cluster {cluster_id}: {points}")

print("\nNoise Points:", noise_points)


Clusters:
Cluster 1: [5, 3, 18, 31, 49, 52, 53, 57, 58, 10, 12, 55, 9, 48, 56, 7, 15, 16, 17, 33, 26, 34, 36, 37, 42, 51, 6, 11, 27, 29, 35, 22, 44, 47, 54, 2, 32, 0, 20, 40, 23, 24, 28, 38, 8, 19, 81, 1, 85, 97, 104, 106, 80, 117, 67, 101, 116, 125, 128, 103, 108, 102, 111, 114, 126, 120, 88, 89, 90, 91, 113, 86, 92, 107]
Cluster 2: [131, 132, 133, 163, 170]
Cluster 3: [140, 139, 142, 161, 162]
Cluster 4: [148, 147, 156, 160, 164, 167, 172, 174, 171]

Noise Points: [4, 13, 14, 21, 25, 30, 39, 41, 43, 45, 46, 50, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 82, 83, 84, 87, 93, 94, 95, 96, 98, 99, 100, 105, 109, 110, 112, 115, 118, 119, 121, 122, 123, 124, 127, 129, 130, 134, 135, 136, 137, 138, 141, 143, 144, 145, 146, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 165, 166, 168, 169, 173, 175, 176, 177]


In [27]:
inverse_transformed_data.shape


(178, 13)

In [28]:
transformed_scaled = StandardScaler().fit_transform(inverse_transformed_data)
distance_matrix = euclidean_distance_matrix(transformed_scaled)
neighborhoods = eps_neighborhood_all(transformed_scaled, epsilon)
print(len(neighborhoods))
core_points, border_points, noise_points = classify_points(neighborhoods, min_pts)
clusters, noise_points = dbscan_clustering(transformed_scaled, epsilon, min_pts)

print("\nClusters:")
for cluster_id, points in clusters.items():
    print(f"Cluster {cluster_id}: {points}")

print("\nNoise Points:", noise_points)


[[0.         3.54291143 3.35212166 ... 6.75260671 6.15472055 7.79187913]
 [3.54291143 0.         4.23465405 ... 6.46856062 5.9473996  7.68579701]
 [3.35212166 4.23465405 0.         ... 6.18074766 5.54950755 6.40344503]
 ...
 [6.75260671 6.46856062 6.18074766 ... 0.         1.65976743 3.58892315]
 [6.15472055 5.9473996  5.54950755 ... 1.65976743 0.         3.61445702]
 [7.79187913 7.68579701 6.40344503 ... 3.58892315 3.61445702 0.        ]]
178

Clusters:
Cluster 1: [5, 3, 10, 18, 31, 49, 52, 53, 58, 48, 17, 55, 9, 42, 56, 7, 15, 16, 33, 34, 57, 2, 32, 35, 51, 30, 40, 22, 29, 44, 47, 54, 26, 0, 20, 23, 24, 28, 36, 37, 12, 11, 38, 6, 8, 81, 27, 1, 85, 97, 104, 106, 80, 117, 67, 116, 125, 101, 105, 107, 128, 103, 108, 102, 111, 114, 120, 126, 72, 91, 92, 82, 86, 88, 90, 87, 89, 113]
Cluster 2: [131, 132, 133, 135, 163, 170, 145, 134, 138, 154, 167, 171, 144, 141, 143, 165, 148, 164, 155, 173, 174, 147, 153, 156, 160, 172, 166, 168]
Cluster 3: [140, 139, 142, 161, 162]

Noise Points: [4, 1

In [29]:
X = np.array([
    [0, 0], [1, 0], [1, 1], [2, 2],
    [3, 1], [3, 0], [0, 1], [3, 2], [6, 3]
]) 
neigh = eps_neighborhood_all(X, 1)
core_, border_, noise_ = classify_points(neigh, 3)
cluste, noise_ = dbscan_clustering(X, 1, 3)

print("\nClusters:")
for cluster_id, points in cluste.items():
    print(f"Cluster {cluster_id}: {points}")

print("\nNoise Points:", noise_)


[[0.         1.         1.41421356 2.82842712 3.16227766 3.
  1.         3.60555128 6.70820393]
 [1.         0.         1.         2.23606798 2.23606798 2.
  1.41421356 2.82842712 5.83095189]
 [1.41421356 1.         0.         1.41421356 2.         2.23606798
  1.         2.23606798 5.38516481]
 [2.82842712 2.23606798 1.41421356 0.         1.41421356 2.23606798
  2.23606798 1.         4.12310563]
 [3.16227766 2.23606798 2.         1.41421356 0.         1.
  3.         1.         3.60555128]
 [3.         2.         2.23606798 2.23606798 1.         0.
  3.16227766 2.         4.24264069]
 [1.         1.41421356 1.         2.23606798 3.         3.16227766
  0.         3.16227766 6.32455532]
 [3.60555128 2.82842712 2.23606798 1.         1.         2.
  3.16227766 0.         3.16227766]
 [6.70820393 5.83095189 5.38516481 4.12310563 3.60555128 4.24264069
  6.32455532 3.16227766 0.        ]]

Clusters:
Cluster 1: [5, 3, 10, 18, 31, 49, 52, 53, 58, 48, 17, 55, 9, 42, 56, 7, 15, 16, 33, 34, 57, 